create table if not exists public.founding_dads (
  id bigint generated by default as identity primary key,
  email text not null unique,
  first_name text,
  biggest_challenge text,
  source text default 'direct',
  created_at timestamptz not null default now()
);

alter table public.founding_dads enable row level security;

create index if not exists founding_dads_created_at_idx
  on public.founding_dads (created_at desc);

comment on table public.founding_dads is
  'Private HalfTimeDad founding member waitlist. Writes occur through the server-side API route.';
