import Link from "next/link";
import FoundingForm from "@/components/FoundingForm";
import NewsletterSignup from "@/components/NewsletterSignup";
import ShareHalfTimeDad from "@/components/ShareHalfTimeDad";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

const principles = [
  ["01", "Take a breath", "Create space before sending the reply, making the decision, or starting the conversation."],
  ["02", "Remove the emotion", "Turn a charged reaction into a clear message that keeps the kids at the center."],
  ["03", "State the facts", "Say what matters without adding fuel, assumptions, or a second argument."],
  ["04", "Respond. Don’t react.", "Choose the response your future self—and your kids—will be glad you sent."],
];

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero section-shell">
      <div className="hero-copy reveal"><p className="kicker">The Founding Hundred · Enrollment open</p><h1>No dad should have to navigate the hardest season of his life alone.</h1><p className="hero-lede">HalfTimeDad is the calm place between the message you receive and the response you choose. Practical tools. Honest perspective. A village built around the kids.</p><div className="hero-actions"><a className="button button-primary" href="#join">Become a Founding Dad</a><Link className="text-link" href="/peace-monitor">Try the Peace Monitor →</Link></div><div className="launch-note"><span className="status-dot" /><span><strong>Founding membership starts now.</strong> Public launch October 1, 2026.</span></div></div>
      <aside className="founder-card reveal reveal-delay"><div className="founder-card-top"><span>Founding Class</span><strong>2026</strong></div><div className="founder-number">#001—100</div><p>Permanent founder numbers for the first one hundred dads who help build the village.</p><div className="founder-grid" aria-hidden="true">{Array.from({length:20},(_,i)=><span key={i}>{String(i+1).padStart(3,"0")}</span>)}</div><p className="founder-card-line">We honor the dads who believed first.</p></aside>
    </section>
    <section className="belief-band"><p>Perspective before reaction.</p><span>Kids over conflict.</span><span>Practical beats perfect.</span><span>No dad does this alone.</span></section>
    <section className="section section-shell" id="philosophy"><div className="section-heading"><p className="kicker">Before you hit send</p><h2>The pause changes everything.</h2><p>The most important feature we will ever build is the space between emotion and action. That is where a better decision begins.</p></div><div className="principle-grid">{principles.map(([n,t,d])=><article className="principle-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section className="story-section" id="story"><div className="story-inner section-shell"><p className="kicker">Why we exist</p><h2>One dad answered the phone. Then another dad did the same.</h2><div className="story-columns"><p>HalfTimeDad began with a simple kind of support: someone who had already walked the road helping another father slow down, read the difficult email twice, and ask what was actually best for the kids.</p><p>Not every dad has that person. We are building the village that makes practical perspective available wherever a dad happens to be—in the school pickup line, at the kitchen table, or sitting in his truck after drop-off.</p></div></div></section>
    <section className="alone-section"><div className="alone-inner section-shell"><p className="kicker">You are not alone</p><p className="alone-copy">Somewhere today, a dad is staring at a message he does not know how to answer. Another is wondering whether he is getting any of this right. Another is trying to rebuild without letting his kids carry the weight.</p><p className="alone-close">He may not know it yet. <strong>But he is not alone.</strong></p></div></section>
    <section className="share-band"><div className="section-shell share-band-inner"><div><p className="kicker">Pass it on</p><h2>Know a dad who could use a calmer place to land?</h2><p>Send him HalfTimeDad. No pitch. Just a practical place to start.</p></div><ShareHalfTimeDad className="button-primary" /></div></section>
    <section className="newsletter-band"><div className="section-shell newsletter-band-inner"><div className="newsletter-band-copy"><p className="kicker">The Sunday Reset</p><h2>One idea. One script. One calmer week.</h2><p>A free weekly note from Founding Dad #001. Practical perspective for dads navigating divorce—delivered every Sunday morning.</p><NewsletterSignup variant="band" /></div><div className="newsletter-preview"><p className="newsletter-preview-label">Latest issue</p><p className="newsletter-preview-subject">&ldquo;You don&rsquo;t have to answer right now&rdquo;</p><p className="newsletter-preview-body">When a message changes the temperature of your whole day, the instinct is to respond immediately. This week: a four-step reset that gives you back the choice.</p><hr /><p className="newsletter-preview-meta">The Sunday Reset &middot; Free &middot; Unsubscribe anytime</p></div></div></section>
    <section className="section section-shell" id="tools"><div className="section-heading split-heading"><div><p className="kicker">The toolbox</p><h2>Built for the decisions that happen in real life.</h2></div><p>Every feature must help a dad think more clearly, reduce stress, strengthen his relationship with his kids, or feel less alone.</p></div><div className="tool-grid"><Link className="tool-card featured" href="/peace-monitor"><span className="tool-status">Available now</span><h3>The Peace Monitor</h3><p>A private, lighthearted way to count the days you kept it clean, spot your own patterns, and put space between the message and the reaction.</p><span className="card-link">Open the monitor →</span></Link><article className="tool-card"><span className="tool-status">In development</span><h3>Message Coach</h3><p>A thoughtful second read that helps remove heat, clarify the facts, and keep the kids at the center.</p><span className="card-link">Founders see it first</span></article><article className="tool-card"><span className="tool-status">In development</span><h3>The Playbook</h3><p>Practical guides for communication, co-parenting, money, routines, and rebuilding.</p><span className="card-link">Built with dads</span></article></div></section>
    <section className="section roadmap-section"><div className="section-shell"><div className="section-heading"><p className="kicker">The road to launch</p><h2>You are not waiting for HalfTimeDad. You are helping build it.</h2></div><div className="roadmap-list"><article><span>01</span><div><p className="kicker">Available now</p><h3>The founding experience</h3><p>Build updates, practical field notes, founder voting, and early tools as they are released.</p></div></article><article><span>02</span><div><p className="kicker">Before launch</p><h3>Tools arrive first for founders</h3><p>Message Coach previews, Peace Monitor access, playbooks, and direct feedback sessions.</p></div></article><article><span>03</span><div><p className="kicker">October 1, 2026</p><h3>Public doors open</h3><p>The complete member experience launches. Founding pricing stays locked while membership remains active.</p></div></article></div></div></section>
    <section className="section section-shell promise-section"><div className="promise-copy"><p className="kicker">Our promise</p><h2>We will never profit from keeping families in conflict.</h2><p>We build practical tools, listen before we build, protect member privacy, and remember that behind every message is a family. HalfTimeDad offers education and peer perspective—not legal, medical, or mental-health advice.</p></div><ul className="promise-list"><li><span>01</span>Put kids first.</li><li><span>02</span>Encourage thoughtful decisions.</li><li><span>03</span>Earn trust every day.</li><li><span>04</span>Build with dads.</li></ul></section>
    <section className="section founding-section" id="join"><div className="section-shell founding-shell"><div className="founding-intro"><p className="kicker">The Founding Hundred</p><h2>Help build the village before the doors open.</h2><p>Membership begins today with build updates, practical resources, founder voting, and early feature access. The full public experience opens October 1, 2026.</p><div className="membership-notes"><span>Permanent founder number</span><span>Founding price locked while active</span><span>Cancel anytime</span></div></div><FoundingForm /></div></section>
    <section className="partner-section"><div className="section-shell partner-inner"><div><p className="kicker">Founding partner</p><h2>Free Range Dad Supply Co.</h2><p>Goods for dads who know the best parts of fatherhood rarely happen indoors—or according to plan.</p></div><a className="button button-secondary" href="https://www.freerangedadsupplyco.com/" target="_blank" rel="noreferrer">Visit Free Range Dad</a></div></section>
  </main><SiteFooter /></>;
}
